### ISSUE TITLE
Proposal: use ubuntu-slim as the base image

### ISSUE THREAD

**Issue by arschles** [deis/workflow-manager#39]
Detailed summary can be found here: deis/workflow-e2e#105 (comment)

In short, if we use gcr.io/google_containers/ubuntu-slim:0.2, we could link our binaries with libc, which would reduce binary size and speed compilation in some cases.

**Comment by bacongobbler** [comment]
@krancour shall I assign this to you, since you're working on the ubuntu-slim move? :)

**Comment by krancour** [comment]
Yes.  I just assigned it.

**Comment by arschles** [comment]
Fixed by #57. closing
